### PR TITLE
Capital Classes

### PR DESCRIPTION
**Pull request by TurBoss**
I hope that this doesn't break anything..
please can you  check my branch before merge?

Thanks
edit: nothing estrange on simulator

### CODE REVIEW

**Comment by TurBoss** [comment]
I use PyCharm to code in python it helps to follow pep8 guidelines
and gitkraken to git stuff, I can have various remote and switch from branch to branch like a monkey :D

**Comment by KurtJacobson** [comment]
Looks good.  I have made quite a few changes to master locally (added notebook to switch between axis and joint DROs). If I merge this pull request and then commit my changes latter tonight is that likely to cause a problem? I don't know git.

I'll check out PyCharm, I have just been using Gedit.  Thanks

**Comment by TurBoss** [comment]
you can merge later if there is some change that conflicts I will change the pull request to accommodate

Thanks

**Comment by KurtJacobson** [comment]
OK, thanks. I don't think it will cause a problem.

**Comment by KurtJacobson** [comment]
I pushed my changes and then merged you pull request. Tested and all seems OK. Thank you for fixing the class names.

**Pull request merged**
