### PR TITLE
Filechooser bookmarks draft

### PR DESCRIPTION
**Pull request by KurtJacobson**

### CODE REVIEW

**Comment by KurtJacobson** [comment]
There was a conflict since we both modified the line specifying the bookmarks file location. I resolved it by simply deleting my changes. Good leaning experience. Git is amazing!

**Comment by TurBoss** [comment]
oops :D how did go?

I didn't make a pull request with the doubt if it was conflicting and fully functional. but if you managed to solve I'm glad to help

did you find any issues?
Thank you

**Comment by TurBoss** [comment]
also sorry for change so many blank spaces...

**Comment by KurtJacobson** [comment]
There were a few issues, but they were very minor.

I am thinking I am going to need to restructure the repository soon so it does not get too cluttered. I'm opening an issue to discuss.

**Pull request merged**
